<?php
/**
 * Created by PhpStorm.
 * User: skyan
 * Date: 21/11/18
 * Time: 22:51
 */?>

<div class="container">
    <h3><i>Tambah Artikel</i></h3>
    <hr>
    <p> <?= $this->flashSession->output(); ?></p>

    <?=  $this->tag->form('artikel/tambah/simpan');  ?>
        <div class="form-group">
            <label for="title">Judul Artikel</label>
            <?= $form->render('judul'); ?>
        </div>

        <div class="form-group">
            <label for="isi">Isi Artikel</label>
            <?= $form->render('isi'); ?>
        </div>

        <div class="form-group">
            <?= $form->render('save'); ?>
            <?= $form->render('post'); ?>
        </div>

<!--        <input type="hidden" name="--><?//= $this->security->getTokenKey() ?><!--" value="--><?//= $this->security->getToken(); ?><!--" >-->

    <?= $this->tag->endForm() ?>

</div>
