<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <?php
            echo $this->tag->getTitle();
            echo $this->tag->stylesheetLink('public/css/bootstrap.min.css');
        ?>
<!--        <link rel="stylesheet" href="--><?php //echo $this->url->get('css/bootstrap.min.css') ?><!--">-->
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
            <a class="navbar-brand" href="#">SkyLine</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"></button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <form class="form-inline my-2 my-lg-0">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        
                    </ul>
                    <?php
                        echo $this->tag->linkTo([
                                'user/login',
                                '<i class="fa fa-sign-in" aria-hidden="true"></i> Login',
                            "class" => "btn btn-light"
                        ]);
                        echo "$nbsp";
                    ?>
                </form>
            </div>
        </nav>
        <div class="container ">
            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> -->
        <script src="js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>
